### PR TITLE
fix #3

### LINKED ISSUE #3: wrong @type
from Keith: The OpenNLP NER service sets the @type to NamedEntity with a category feature that contains the correct Uri (Date, Location, etc).  I thought we had decided that the @type would be one of Uri.DATE, Uri.LOCATION, etc.?

### PR DESCRIPTION
**Pull request by keighrim**
resolving #3

### CODE REVIEW

**Comment by chunqishi** [comment]
Hi, Keigh,

You should create new branch 2.0.1.
And merge our modification into this new branch, instead of api2.0.

Now we cannot easily read any code from api2.0, but we have online service
that running under api2.0.

This is not good way.

Best,

## 

Chunqi

**Comment by keighrim** [comment]
Yep, that makes sense. 
I'm reverting this merge.

**Comment by chunqishi** [comment]
Thank you ~
I would like rename the api2.0 into v2.0.0 :- )

## 

Chunqi

**Comment by keighrim** [comment]
Sure, go ahead. I was actually thinking of rename it too just now :)

**Comment by chunqishi** [comment]
Great,  I finished copy your merge into v2.0.1 and api2.0 into v2.0.0 for
both opennlp and stanford.

Let us work together on v2.0.1.

Best.

## 

Chunqi

**Pull request merged**
